#!/bin/bash
echo "Variables...."
read -p "Size of .img? [Add 'M' in the end.... (For MB) ] " SIZE
#read -p "Version? [Int] " VERSION

echo "Making .IMG...."
fallocate -l $SIZE blue.img
mkfs.ext4 blue.img
mount -w -o loop blue.img work/

echo "Copying...."
cp -av in/* work/
#echo "set VERSION=$VERSION" > work/version
#chmod +x work/version
umount work/
cp blue.img out/blue.img

echo "Cleaning up..."
rm blue.img

echo "Done! :)"
exit
