#!/bin/bash
mkdir in
cd in

mkdir payload
touch blue.sh


echo "#!/bin/bash" > blue.sh

read -p "What key to check for?  " KEYORIGIN
echo "KEY=/blue/keys/$KEYORIGIN
if test -f "\$KEY"; then

    echo \"\$KEY exists, proceeding...\"

##
fi" >> blue.sh


touch key.sh
read -p "New key to be added?  " NEWKEY
echo "touch /blue/keys/$NEWKEY" > key.sh

